language: java
script: mvn clean install
jdk:
  - oraclejdk8
services:
  - mongodb
before_script:
  - sleep 15
  - mongo test --eval 'printjson(db.getCollectionNames())'
  - mongo --eval 'db.home-control.insert({username:"test test", password:"test"});'
notifications:
  email: false
