language: java
sudo: false
script: mvn clean install -DskipIntegrationTests
jdk:
  - oraclejdk8
services:
  - mongodb
before_script:
  - sleep 15
  - mongo use home-control
notifications:
  email: false
